spring:
  application:
    name: Keyclock
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
      client:
        registration:
          keycloak:
            client-id: admin-cli
            client-secret: rJFYw7hNjcIT3J8wgZm7vxqauiDaHZ9k
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/auth/login/oauth2/code/keycloak"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

server:
  port: 8082
  servlet:
    context-path: /auth

app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: rJFYw7hNjcIT3J8wgZm7vxqauiDaHZ9k
    realm: Amine
    serverUrl: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka
    register-with-eureka: true